name: Limit Issue Creation

on:
  issues:
    types: [opened]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if not owner or admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_CREATOR=$(jq -r .issue.user.login "$GITHUB_EVENT_PATH")
          REPO_OWNER=$(jq -r .repository.owner.login "$GITHUB_EVENT_PATH")
          REPO_ADMINS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/collaborators?affiliation=direct" | jq -r '.[] | select(.permissions.admin == true) | .login')

          IS_ADMIN=false
          for ADMIN in $REPO_ADMINS; do
            if [ "$ISSUE_CREATOR" == "$ADMIN" ]; then
              IS_ADMIN=true
              break
            fi
          done

          if [ "$ISSUE_CREATOR" != "$REPO_OWNER" ] && [ "$IS_ADMIN" != true ]; then
            ISSUE_NUMBER=$(jq -r .issue.number "$GITHUB_EVENT_PATH")
            curl -X PATCH \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER \
              -d '{"state": "closed"}'

            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
              -d '{"body": "This issue was automatically closed because only the repository owner or admins can create issues."}'
          fi
